export class Status {
  static ServerOffline = -1;
  static NoError = 0;
  static Inid = 1;
  static NameShort = 2;
  static PasswordShort = 3;
  static PasswordInid = 4;
  static NameInid = 5;
  static AddUserFailed = 6;
  static UserAlreadyExists = 7;
  static InvalidPassword = 8;
  static PasswordLong = 9;
  static NameLong = 10;
  static YoutubeFetchFailure = 11;
  static YoutubeSearchFailure = 12;
  static YoutubeGetFailure = 13;
  static YoutubeGetInfoFailure = 14;
  static YoutubeGetChartsFailure = 15;
  static PlaylistIdAlreadyExists = 16;
  static AddHistoryFailed = 17;
}
